#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "../../..");
const read = (file) => fs.readFileSync(path.join(here, file), "utf8");
const matrix = JSON.parse(read("FAMILY_RELATIONS_MATRIX.json"));
const schema = JSON.parse(read("CANONICAL_TYPED_RECORD.schema.json"));
const html = read("index.html");
const js = read("app.js");
const browserData = read("matrix.data.js");
const kappa = JSON.parse(read("KAPPA_RATH_100_FOLD_RECORD.json"));
const multiGrid = JSON.parse(read("MULTI_GRID_RELATION_LEDGER.json"));
const multiGridBrowserData = read("multi-grid.data.js");
const multiGridBrowserContext = {window: {}};
vm.runInNewContext(multiGridBrowserData, multiGridBrowserContext);
const provenance = JSON.parse(read("MULTI_GRID_VISUAL_PROVENANCE_2026-10-07.json"));
const lineage = JSON.parse(read("GEOMETRIA_NOVA_RESONANCE_CATHEDRAL_INTAKE_2026-10-07.json"));
const recovery = JSON.parse(read("RECOVERY_AND_GRID_OPERATOR_RESULTS_2026-10-07.json"));
const browserContext = {window: {}};
vm.runInNewContext(browserData, browserContext);
const checks = [];
const check = (name, ok) => checks.push({name, ok: Boolean(ok)});

check("matrix schema", matrix.schema === "nexah.family-relations-matrix/1.0.0");
check("eleven instrument groups", matrix.instruments.length === 11);
check("eleven typed relations", matrix.relations.length === 11);
check("unique instrument ids", new Set(matrix.instruments.map((x) => x.id)).size === matrix.instruments.length);
check("relation endpoints resolve", matrix.relations.every((r) => matrix.instruments.some((x) => x.id === r.source) && matrix.instruments.some((x) => x.id === r.target)));
check("all source targets exist", matrix.instruments.every((x) => fs.existsSync(path.resolve(here, x.path))));
check("browser data equals matrix", JSON.stringify(browserContext.window.NEXAH_OBSERVATORY_MATRIX) === JSON.stringify(matrix));
check("canonical eight fields", schema.required.length === 9 && ["carrier","state","operator","view","fiber","return","residual","evidence"].every((x) => schema.required.includes(x)));
check("total report present", fs.existsSync(path.join(here, "NEXAH_LIFE01_LIFE06D_TOTAL_REPORT_2026-10-07.md")));
check("negative results retained", /LIFE04, LIFE04B and LIFE06C remain visible valid-negative/.test(read("01_RESULT_ASSESSMENT.md")));
check("no remote runtime", !/(https?:\/\/|cdn\.|unpkg|jsdelivr)/i.test(html + js));
check("responsive UI", /@media\(max-width:/.test(read("styles.css")));
check("Navigator connection", /NAVIGATION\/APP\/index\.html#observatory/.test(html));
check("Mission Control return connection", /MISSION_CONTROL_RETURN_TRANSITION_IDENTIFIABILITY/.test(html));
check("Mission Control HTML target exists", fs.existsSync(path.resolve(here, "../../../../../00 EXECUTIVE/NEXAH-Mission-Control/INTERNAL_NAVIGATOR/index.html")));
check("claim ceiling visible", /kein universeller Operator/.test(html) && /does not establish one universal operator/.test(JSON.stringify(matrix)));
check("kappa carrier is inclusive 101-state set", kappa.carrier.cardinality === 101);
check("kappa quotient identity", kappa.quotient.cardinality === 51 && kappa.quotient.interior_pairs.count === 49 && kappa.quotient.boundary_pair.join(",") === "0,100" && kappa.quotient.hinge_fixed_point[0] === 50);
check("kappa exact arithmetic", Array.from({length: 49}, (_, i) => i + 1).every((x) => x + (100 - x) === 100));
check("kappa UI present", /id="kappa-grid"/.test(html) && /data-kappa-lower/.test(js));
check("Rath claim boundary retained", /declared bridge construction/.test(kappa.claim_boundary) && /Historical operator identity remains open/.test(html));
check("multi-grid ledger schema", multiGrid.schema === "nexah.multi-grid-relation-ledger/1.1.0");
check("fifteen grid and model nodes", multiGrid.nodes.length === 15);
check("fifteen typed grid and model edges", multiGrid.edges.length === 15);
check("multi-grid node ids unique", new Set(multiGrid.nodes.map((x) => x.id)).size === multiGrid.nodes.length);
check("multi-grid endpoints resolve", multiGrid.edges.every((edge) => multiGrid.nodes.some((node) => node.id === edge.source) && multiGrid.nodes.some((node) => node.id === edge.target)));
check("multi-grid browser data equals ledger", JSON.stringify(multiGridBrowserContext.window.NEXAH_MULTI_GRID_LEDGER) === JSON.stringify(multiGrid));
check("multi-grid statuses bounded", multiGrid.edges.every((edge) => ["exact","bounded","declared","candidate","visual-only"].includes(edge.status)));
check("multi-grid UI and finding present", /id="multigrid-nodes"/.test(html) && /multi-grid\.data\.js/.test(html) && fs.existsSync(path.join(here, "MULTI_GRID_RELATION_FINDING_2026-10-07.md")));
check("no universal grid claim", /does not assert one universal grid/.test(multiGrid.claim_boundary));
check("visual provenance schema", provenance.schema === "nexah.owner-visual-provenance/1.0.0");
check("six visual sources sealed", provenance.assets.length === 6 && new Set(provenance.assets.map((asset) => asset.sha256)).size === 6 && provenance.assets.every((asset) => /^[a-f0-9]{64}$/.test(asset.sha256)));
check("model-lineage intake schema", lineage.schema === "nexah.model-lineage-intake/1.0.0");
check("nine GLB assets bound", lineage.model_assets.length === 9 && new Set(lineage.model_assets.map((asset) => asset.sha256)).size === 9 && lineage.model_assets.every((asset) => /^[a-f0-9]{64}$/.test(asset.sha256)));
check("external GLB files retained", lineage.model_assets.every((asset) => fs.existsSync(asset.path) && fs.statSync(asset.path).size === asset.bytes));
check("external GLB hashes match intake", lineage.model_assets.every((asset) => fs.existsSync(asset.path) && crypto.createHash("sha256").update(fs.readFileSync(asset.path)).digest("hex") === asset.sha256));
const cathedralInheritance = lineage.verified_relations.find((relation) => relation.source === "RC08" && relation.target === "RC88");
check("Cathedral 492 of 494 inheritance bound", cathedralInheritance?.result === "492/494 source names retained" && cathedralInheritance?.missing?.join(",") === "CameraProxy,LightBurst" && cathedralInheritance?.added_named_nodes === 17588);
check("nine owner-session visuals hash-bound", lineage.owner_screenshot_session.assets.length === 9 && lineage.owner_screenshot_session.assets.every((asset) => /^[a-f0-9]{64}$/.test(asset.sha256)));
check("five USDZ names remain unresolved", lineage.visible_usdz_names.length === 5 && lineage.visible_usdz_names.every((asset) => /BINARY_NOT_RECOVERED/.test(asset.status)));
check("five GLB source-format counterparts recovered", recovery.usdz_recovery.usdz_binaries_found === 0 && recovery.usdz_recovery.source_format_counterparts_found === 5 && recovery.usdz_recovery.counterparts.length === 5);
check("recovered GLB counterparts hash-match", recovery.usdz_recovery.counterparts.every((asset) => fs.existsSync(asset.path) && fs.statSync(asset.path).size === asset.bytes && crypto.createHash("sha256").update(fs.readFileSync(asset.path)).digest("hex") === asset.sha256));
check("three retained grids satisfy reconstructed template", recovery.status === "PASS_BOUNDED_RECONSTRUCTION" && recovery.retained_grid_binary_tests.length === 3 && recovery.retained_grid_binary_tests.every((grid) => Object.values(grid.template_checks).every(Boolean)));
check("six grid operator tests pass bounded return", recovery.operator_tests.length === 6 && recovery.operator_tests.every((test) => test.forward_axis_injective && test.source_address_roundtrip_exact && test.max_2d_coordinate_residual > 0));
check("Rath semantics remain open", recovery.rath_49_51.arithmetic_status.startsWith("EXACT_") && recovery.rath_49_51.historical_semantic_operator_recovered === false && /SEMANTIC_IDENTITY_OPEN/.test(recovery.rath_49_51.status));
check("recovery script and finding present", fs.existsSync(path.join(here, "recovery-and-grid-operator.mjs")) && fs.existsSync(path.join(here, "RECOVERY_AND_GRID_OPERATOR_FINDING_2026-10-07.md")));
check("model-lineage UI present", /id="lineage-title"/.test(html) && /492 \/ 494/.test(html) && /GEOMETRIA_NOVA_RESONANCE_CATHEDRAL_INTAKE/.test(html));
check("Mission Control model-lineage return", /Owner-directed model-lineage intake/.test(fs.readFileSync(path.join(repo, "SCIENCE_LAB/MISSION_CONTROL_RETURN_TRANSITION_IDENTIFIABILITY_OBSERVATORY_V1_2026-10-07.md"), "utf8")));
check("Mission Control reciprocal Observatory card", /id="transition-observatory"/.test(fs.readFileSync(path.resolve(here, "../../../../../00 EXECUTIVE/NEXAH-Mission-Control/INTERNAL_NAVIGATOR/index.html"), "utf8")));
check("controlling open questions present", fs.existsSync(path.join(here, "OPEN_QUESTIONS_AND_DEFERRED_WORK_2026-10-07.md")) && /Closed negatives/.test(read("OPEN_QUESTIONS_AND_DEFERRED_WORK_2026-10-07.md")));
check("final resume present", fs.existsSync(path.join(here, "FINAL_RESUME_2026-10-07.md")) && /INTERNAL CYCLE CLOSED/.test(read("FINAL_RESUME_2026-10-07.md")));
check("V1.1 predecessor freeze retained", fs.existsSync(path.join(here, "FREEZE_RECORD_V1_1_MULTI_GRID_ADDENDUM_2026-10-07.md")) && /V1\.1 freeze/.test(html));
check("V1.2 predecessor freeze retained", fs.existsSync(path.join(here, "FREEZE_RECORD_V1_2_GEOMETRIA_NOVA_MODEL_LINEAGE_ADDENDUM_2026-10-07.md")) && /V1\.2 freeze/.test(html));
check("V1.3 freeze present and visible", fs.existsSync(path.join(here, "FREEZE_RECORD_V1_3_RECOVERY_AND_OPERATOR_ADDENDUM_2026-10-07.md")) && /OBSERVATORY V1\.3/.test(html) && /V1\.3 frozen/.test(html));

const failed = checks.filter((x) => !x.ok);
const result = {schema: "nexah.observatory-validation/1.0.0", status: failed.length ? "FAIL" : "PASS", checks: checks.length, passed: checks.length - failed.length, failed: failed.map((x) => x.name), detail: checks};
fs.writeFileSync(path.join(here, "results/OBSERVATORY_VALIDATION_REPORT.json"), JSON.stringify(result, null, 2) + "\n");
console.log(JSON.stringify(result, null, 2));
if (failed.length) process.exitCode = 1;
