#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const source = path.join(here, "UTG_FRAMEWORK_BINDER_V1_2026-10-06.json");
const target = path.resolve(here, "../../APP/utg.internal.js");
const binder = JSON.parse(fs.readFileSync(source, "utf8"));

if (!Array.isArray(binder.visuals) || !Array.isArray(binder.maturity_levels) || !Array.isArray(binder.media_constellations) || !Array.isArray(binder.formal_candidates)) {
  throw new Error("UTG binder is missing a required array");
}

const serialized = JSON.stringify(binder).replaceAll("</script", "<\\/script");
const output = `/* Generated by UNIFIED_TRANSITION_GEOMETRY_2026-10-06/build_utg_data.mjs. */\nwindow.NEXAH_UTG_BINDER = ${serialized};\n`;
fs.writeFileSync(target, output);
console.log(JSON.stringify({
  status: "PASS",
  target: path.relative(here, target),
  visuals: binder.visuals.length,
  maturity_levels: binder.maturity_levels.length,
  constellations: binder.media_constellations.length,
  formal_candidates: binder.formal_candidates.length,
  bytes: Buffer.byteLength(output)
}, null, 2));
