#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const source = path.join(here, "PRIME_BRIDGE_LINEAGE_BINDER_V1_2026-10-06.json");
const target = path.resolve(here, "../../APP/lineage.internal.js");
const binder = JSON.parse(fs.readFileSync(source, "utf8"));

if (!Array.isArray(binder.visuals) || !Array.isArray(binder.glb_assets) || !Array.isArray(binder.lineage_nodes) || !Array.isArray(binder.relations)) {
  throw new Error("Lineage binder is missing a required array");
}

const serialized = JSON.stringify(binder).replaceAll("</script", "<\\/script");
const output = `/* Generated by PRIME_BRIDGE_LINEAGE_2026-10-06/build_lineage_data.mjs. */\nwindow.NEXAH_LINEAGE_BINDER = ${serialized};\n`;
fs.writeFileSync(target, output);
console.log(JSON.stringify({
  status: "PASS",
  target: path.relative(here, target),
  visuals: binder.visuals.length,
  glb_assets: binder.glb_assets.length,
  nodes: binder.lineage_nodes.length,
  relations: binder.relations.length,
  bytes: Buffer.byteLength(output)
}, null, 2));
