#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const source = path.resolve(here, "../BUILD/registry-dist/navigator.internal.json");
const admissionSource = path.resolve(here, "../BUILD/registry-dist/rejected-public-items.json");
const publicSource = path.resolve(here, "../BUILD/registry-dist/navigator.public.json");
const target = path.resolve(here, "data.internal.js");

const manifest = JSON.parse(fs.readFileSync(source, "utf8"));
const admission = JSON.parse(fs.readFileSync(admissionSource, "utf8"));
const publicManifest = JSON.parse(fs.readFileSync(publicSource, "utf8"));
if (manifest.profile !== "internal") throw new Error(`Expected internal profile, received ${manifest.profile}`);
if (!Array.isArray(manifest.entities) || !Array.isArray(manifest.relations)) throw new Error("Manifest is missing entity or relation arrays");

const serialized = JSON.stringify(manifest).replaceAll("</script", "<\\/script");
const serializedAdmission = JSON.stringify(admission).replaceAll("</script", "<\\/script");
const release = {
  publication_authorized: publicManifest.publication_authorized,
  release_state: publicManifest.release_state,
  public_entity_count: publicManifest.entities.length,
  selection_record_id: publicManifest.governance?.selection_record_id
};
const serializedRelease = JSON.stringify(release);
const output = `/* Generated by build_app_data.mjs from validated internal Navigator build outputs. */\nwindow.NEXAH_NAVIGATOR_MANIFEST = ${serialized};\nwindow.NEXAH_NAVIGATOR_ADMISSION = ${serializedAdmission};\nwindow.NEXAH_NAVIGATOR_RELEASE = ${serializedRelease};\n`;
fs.writeFileSync(target, output);
console.log(JSON.stringify({ status: "PASS", source: path.relative(here, source), admission_source: path.relative(here, admissionSource), public_source: path.relative(here, publicSource), target: path.basename(target), entities: manifest.entities.length, relations: manifest.relations.length, rejected_public_items: admission.rejected.length, publication_authorized: release.publication_authorized, bytes: Buffer.byteLength(output) }, null, 2));
