#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const sourcePath = path.resolve(here, "../NAVIGATOR_ENTRY_CONTENT_V1_2026-10-07.json");
const deltaPath = path.resolve(here, "../NAVIGATOR_V2_DELTA_MULTI_VIEW_RECONSTRUCTION_2026-10-07.json");
const outputPath = path.join(here, "entry.internal.js");
const data = JSON.parse(fs.readFileSync(sourcePath, "utf8"));
const delta = JSON.parse(fs.readFileSync(deltaPath, "utf8"));

if (delta.status !== "STAGED_NOT_ADMITTED" || delta.v1_freeze_unchanged !== true) {
  throw new Error("Navigator v2 preview delta must remain staged and preserve the v1 freeze.");
}
data.schema = "nexah-navigator-entry-content/2.0.0-preview";
data.content_id = "NEXAH:NAVIGATOR:ENTRY:V2:PREVIEW";
data.preview_status = "INTERNAL_V2_PREVIEW_NOT_PUBLIC";
data.featured_evidence_case = delta.candidate;

const multiViewFocus = data.current_focus.find((item) => item.focus_id === "FOCUS:OIL_RIS_MULTI_LENS");
if (!multiViewFocus) throw new Error("Missing OIL/RIS focus record for v2 preview overlay.");
Object.assign(multiViewFocus, {
  display_title: "Reconstructing structure from incomplete views",
  short_title: "Multi-View Reconstruction",
  plain_summary: "Three individually incomplete views recover the declared relation state only when their addresses and overlaps align. Provenance remains unknown, and mismatch returns ABSTAIN.",
  first_use: "Multi-view reconstruction is the human-facing method. OIL/RIS remains the internal provenance label of this case.",
  lifecycle: "current_bounded",
  status_label: "9/9 vertical gates · human review pending",
  why_current: "The first bounded source-to-test-to-GLB-to-Human-Return vertical is now assembled and machine-checked.",
  next_step: "One independent reader answers the four review questions; record time, confidence and confusion.",
  primary_route: "evidence",
  primary_action: "Open the evidence case",
  controlling_record: delta.candidate.controlling_records[2],
  claim_boundary: delta.candidate.claim_ceiling
});

const requiredTopLevel = ["schema", "content_id", "maintained", "profile", "publication_authorized", "domains", "current_focus", "terms", "featured_evidence_case"];
const missing = requiredTopLevel.filter((key) => !(key in data));
if (missing.length) throw new Error(`Missing entry-content fields: ${missing.join(", ")}`);
if (data.profile !== "internal") throw new Error("Entry content must remain internal.");
if (data.publication_authorized !== false) throw new Error("Entry content must remain fail-closed.");
if (data.domains.length !== 6) throw new Error(`Expected six domains, received ${data.domains.length}.`);
if (data.current_focus.length !== 5) throw new Error(`Expected five current-focus entries, received ${data.current_focus.length}.`);

const ids = (items, key) => items.map((item) => item[key]);
for (const [label, values] of [
  ["domain", ids(data.domains, "domain_id")],
  ["focus", ids(data.current_focus, "focus_id")],
  ["term", ids(data.terms, "term_id")]
]) {
  if (values.some((value) => !value)) throw new Error(`Missing ${label} ID.`);
  if (new Set(values).size !== values.length) throw new Error(`Duplicate ${label} ID.`);
}

const domainIds = new Set(ids(data.domains, "domain_id"));
for (const item of data.current_focus) {
  for (const domainId of item.domain_ids || []) {
    if (!domainIds.has(domainId)) throw new Error(`${item.focus_id} references unknown domain ${domainId}.`);
  }
  if (!item.controlling_record || !item.status_label || !item.claim_boundary) {
    throw new Error(`${item.focus_id} lacks a controlling record, status or claim boundary.`);
  }
}

const banner = "// Generated by build_entry_data.mjs. Do not edit by hand.\n";
fs.writeFileSync(outputPath, `${banner}window.NEXAH_NAVIGATOR_ENTRY = ${JSON.stringify(data, null, 2)};\n`);
console.log(JSON.stringify({ status: "PASS", domains: data.domains.length, focus: data.current_focus.length, terms: data.terms.length, output: path.relative(here, outputPath) }, null, 2));
